--Criação de software (web e mobile) de clínica médica
--Atividade do curso técnico Desenvolvimento de Sistemas
--Senai Informática São Paulo - 2019
--Instrutores: Helena Strada e Fernando Henrique Guerra
--Aluno: Daniel Roncaglia Correia dos Santos

--DDL - LINGUAGEM DE CRIAÇÃO DE DADOS

--CRIA BANCO DE DADOS DO PROGRAMA FEITO PARA O MEDICAL GROUP
CREATE DATABASE SENAI_MEDICAL_GROUP_2TT

USE SENAI_MEDICAL_GROUP_2TT

--CRIA A TABELA DE USUARIOS
CREATE TABLE USUARIOS(
	-- COLUNA TIPO_DADOS CARACTERÍSTICAS CHAVE
	ID_USUARIO INT IDENTITY PRIMARY KEY
	,ID_TIPO INT FOREIGN KEY REFERENCES TIPO(ID_TIPO)
	,EMAIL_USUARIO VARCHAR(200)NOT NULL UNIQUE
	,SENHA_USUARIO VARCHAR(200) NOT NULL DEFAULT(RAND()*10)
);

--CRIA A TABELA TIPOS USUARIOS
CREATE TABLE TIPO(
	-- COLUNA TIPO_DADOS CARACTERÍSTICAS CHAVE
	ID_TIPO INT PRIMARY KEY IDENTITY
	,TIPO_USUARIO VARCHAR(200) NOT NULL UNIQUE
);

--CRIA A TABELA PACIENTES
CREATE TABLE PACIENTES(
	-- COLUNA TIPO_DADOS CARACTERÍSTICAS CHAVE
	ID_PACIENTE INT PRIMARY KEY IDENTITY
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID_USUARIO)
	,NOME_PACIENTE VARCHAR(200) NOT NULL
	,NASCIMENTO DATE NOT NULL
	,RG CHAR(11) NOT NULL
	,CPF CHAR(11) NOT NULL
	,TELEFONE CHAR(14) NOT NULL
	,ENDERECO VARCHAR(200) NOT NULL
	,INFORMACOES_PACIENTE TEXT
);

--CRIA A TABELA MÉDICOS
CREATE TABLE MEDICOS(
	-- COLUNA TIPO_DADOS CARACTERÍSTICAS CHAVE
	ID_MEDICO INT PRIMARY KEY IDENTITY
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID_USUARIO)
	,NOME_MEDICO VARCHAR(250) NOT NULL
	,CRM_MEDICO CHAR(7) NOT NULL
	,ID_ESPECIALIDADE INT FOREIGN KEY REFERENCES ESPECIALIDADES(ID_ESPECIALIDADE)
	,ID_CLINICA INT FOREIGN KEY REFERENCES CLINICA(ID_CLINICA)
);

--CRIA A TABELA CONSULTAS
CREATE TABLE CONSULTAS(
	-- COLUNA TIPO_DADOS CARACTERÍSTICAS CHAVE
	ID_PACIENTE INT FOREIGN KEY REFERENCES PACIENTES(ID_PACIENTE)
	,ID_MEDICO  INT FOREIGN KEY REFERENCES MEDICOS(ID_MEDICO)
	,DATA_HORARIO DATETIME NOT NULL
	,DESCRICAO_CONSULTA TEXT
	,SITUACAO_CONSULTA	CHAR(50) NOT NULL
);

--CRIA TABELA ESPECIALIDADES
CREATE TABLE ESPECIALIDADES(
	-- COLUNA TIPO_DADOS CARACTERÍSTICAS CHAVE
	ID_ESPECIALIDADE INT PRIMARY KEY IDENTITY
	,ESPECIALIDADE_MEDICO CHAR(200) NOT NULL
);

--CRIA TABELA CLINICA
CREATE TABLE CLINICA(
	-- COLUNA TIPO_DADOS CARACTERÍSTICAS CHAVE
	ID_CLINICA  INT IDENTITY PRIMARY KEY
	,NOME_CLINICA VARCHAR(200) NOT NULL
	,CNPJ VARCHAR(14) NOT NULL
	,RAZAO CHAR(200) NOT NULL
	,ENDERECO CHAR(200) NOT NULL
);

--EXEMPLO DE ALTERAÇÃO DA TABELA CONSULTA
ALTER TABLE CONSULTAS
ADD OUTROS TEXT
SELECT * FROM CONSULTAS;

ALTER TABLE PACIENTES
ADD IDADE INT
SELECT * FROM PACIENTES;

ALTER TABLE CONSULTAS
ADD ID_CONSULTAS INT IDENTITY PRIMARY KEY