--Criação de software (web e mobile) de clínica médica
--Atividade do curso técnico Desenvolvimento de Sistemas
--Senai Informática São Paulo - 2019
--Instrutores: Helena Strada e Fernando Henrique Guerra
--Aluno: Daniel Roncaglia Correia dos Santos

-- DQL - LINGUAGEM DE CONSULTA DE DADOS

--FAZ A SELEÇÃO DE DADOS NAS TABELAS DO BANCO DE DADOS - QUERY
USE SENAI_MEDICAL_GROUP_2TT;

--SELECIONA OS DADOS DA TABELA CONSULTA
SELECT * FROM CONSULTAS;

--SELECIONA OS HORÁRIOS DA TABELA CONSULTA
SELECT DATA_HORARIO FROM CONSULTAS;

--SELECIONA AS CONSULTAS DO PACIENTE 2
SELECT * FROM CONSULTAS WHERE ID_PACIENTE = 2;

--SELECIONA A TABELA CONSULTAS MOSTRANDO O NOME E INFORMAÇÕES DOS MÉDICOS
SELECT * FROM MEDICOS INNER JOIN CONSULTAS ON MEDICOS.ID_MEDICO = CONSULTAS.ID_MEDICO;

--SELECIONA A TABELA PACIENTES MOSTRANDO CONSULTAS REALIZADAS E AGENDADAS
SELECT * FROM PACIENTES RIGHT JOIN CONSULTAS ON PACIENTES.ID_PACIENTE = CONSULTAS.ID_PACIENTE;

--SELECIONA A TABELA MÉDICOS MOSTRANDO AS ESPECIALIDADES DISPONÍVEIS
SELECT * FROM MEDICOS LEFT JOIN ESPECIALIDADES ON MEDICOS.ID_ESPECIALIDADE = ESPECIALIDADES.ID_ESPECIALIDADE;

--SELECIONA A TABELA MÉDICOS COM VINCULACAO DAS CLINICAS
SELECT * FROM MEDICOS INNER JOIN CLINICA ON MEDICOS.ID_CLINICA = CLINICA.ID_CLINICA;

--SELECIONA A TABELA CONSULTAS MOSTRANDO O NOME E INFORMAÇÕES DOS MÉDICOS E DOS PACIENTES
--EXEMPLO COM USO DE PROCEDURE
CREATE PROCEDURE CONSULTA_COMPLETA
AS
BEGIN
SELECT * FROM CONSULTAS 
INNER JOIN MEDICOS ON CONSULTAS.ID_MEDICO = MEDICOS.ID_MEDICO
INNER JOIN PACIENTES ON CONSULTAS.ID_PACIENTE = PACIENTES.ID_PACIENTE
END
GO
EXEC CONSULTA_COMPLETA

--CALCULANDO A IDADE DOS PACIENTES
SELECT DATEDIFF(DAY, NASCIMENTO, GETDATE()) / 365 AS IDADE FROM PACIENTES

--CONTANDO MÉDICOS POR ESPECIALIDADE
CREATE PROCEDURE MEDICO_POR_ESPECIALIDADE
	@ESPECIALIDADES VARCHAR(255)
AS
BEGIN
	SELECT COUNT(ID) AS MEDICOS_POR_ESPECIALIDADE FROM MEDICOS WHERE ID_ESPECIALIDADE = @ESPECIALIDADES
END
GO
EXEC MEDICO_POR_ESPECIALIDADE

--FAZENDO BACKUP DO BANCO DE DADOS
CREATE PROCEDURE BACKUP_BD
AS
BEGIN
	BACKUP DATABASE SENAI_MEDICAL_GROUP_2TT
	TO DISK = 'C:\db\SENAI_MEDICAL_GROUP_2TT.BAK'
END
GO
EXEC BACKUP_BD