--Criação de software (web e mobile) de clínica médica
--Atividade do curso técnico Desenvolvimento de Sistemas
--Senai Informática São Paulo - 2019
--Instrutores: Helena Strada e Fernando Henrique Guerra
--Aluno: Daniel Roncaglia Correia dos Santos

--DBL - LINGUAGEM DE MANIPULAÇÃO DE DADOS

--INSERÇÃO DE DADOS NAS TABELAS DO BANCO DE DADOS

USE SENAI_MEDICAL_GROUP_2TT;

--CHAMA DADOS PARA TABELA OS DADOS DO ARQUIVO TIPO USUARIO
BULK INSERT TIPO
FROM 'C:\db\tipo.csv'
	WITH (
		FORMAT = 'csv',
		FIRSTROW = 2,
		FIELDTERMINATOR = ';',
		ROWTERMINATOR = '\n',
		CODEPAGE = 'ACP', 
		DATAFILETYPE = 'Char'
	);

SELECT * FROM TIPO

--CHAMA DADOS PARA TABELA OS DADOS DO ARQUIVO ESPECIALIDADES
BULK INSERT ESPECIALIDADES
FROM 'C:\db\especialidades.csv'
	WITH (
		FORMAT = 'csv',
		FIRSTROW = 2,
		FIELDTERMINATOR = ';',
		ROWTERMINATOR = '\n',
		CODEPAGE = 'ACP', 
		DATAFILETYPE = 'Char'
	);

SELECT * FROM ESPECIALIDADES

--CHAMA DADOS PARA TABELA OS DADOS DO ARQUIVO CLINICA
BULK INSERT CLINICA
FROM 'C:\db\clinica.csv'
	WITH (
		FORMAT = 'csv',
		FIRSTROW = 2,
		FIELDTERMINATOR = ';',
		ROWTERMINATOR = '\n',
		CODEPAGE = 'ACP', 
		DATAFILETYPE = 'Char'
	);

SELECT * FROM CLINICA

--CHAMA DADOS PARA TABELA OS DADOS DO ARQUIVO USUARIOS
BULK INSERT USUARIOS
FROM 'C:\db\usuarios.csv'
	WITH (
		FORMAT = 'csv',
		FIRSTROW = 2,
		FIELDTERMINATOR = ';',
		ROWTERMINATOR = '\n',
		CODEPAGE = 'ACP', 
		DATAFILETYPE = 'Char'
	);

SELECT * FROM USUARIOS

--CHAMA DADOS PARA TABELA OS DADOS DO ARQUIVO PACIENTES
BULK INSERT PACIENTES
FROM 'C:\db\pacientes.csv'
	WITH (
		FORMAT = 'csv',
		FIRSTROW = 2,
		FIELDTERMINATOR = ';',
		ROWTERMINATOR = '\n',
		CODEPAGE = 'ACP', 
		DATAFILETYPE = 'Char'
	);

SELECT * FROM PACIENTES

--CHAMA DADOS PARA TABELA OS DADOS DO ARQUIVO MEDICOS
BULK INSERT MEDICOS
FROM 'C:\db\medicos.csv'
	WITH (
		FORMAT = 'csv',
		FIRSTROW = 2,
		FIELDTERMINATOR = ';',
		ROWTERMINATOR = '\n',
		CODEPAGE = 'ACP', 
		DATAFILETYPE = 'Char'
	);

SELECT * FROM MEDICOS

--CHAMA DADOS PARA TABELA OS DADOS DO ARQUIVO CONSULTAS
BULK INSERT CONSULTAS
FROM 'C:\db\consultas.csv'
	WITH (
		FORMAT = 'csv',
		FIRSTROW = 2,
		FIELDTERMINATOR = ';',
		ROWTERMINATOR = '\n',
		CODEPAGE = 'ACP', 
		DATAFILETYPE = 'Char'
	);

SELECT * FROM CONSULTAS

--EXEMPLO DE INSERÇÃO, ALTERAÇÃO E ELIMINAÇÃO NA TABELA ESPECIALIDADE
INSERT INTO ESPECIALIDADES (ESPECIALIDADE_MEDICO) VALUES ('Veterinária');
UPDATE ESPECIALIDADES SET ESPECIALIDADE_MEDICO = 'Medicina Veterinária' WHERE ID_ESPECIALIDADE = 18;
DELETE FROM ESPECIALIDADES  WHERE ID_ESPECIALIDADE = 18;
SELECT * FROM ESPECIALIDADES;